// MARQUEE Heavy derivative build; SIL OFL 1.1. Requires @napi-rs/canvas 0.1.x.
const fs=require('fs'),path=require('path'),zlib=require('zlib');
const {Path2D,PathOp,StrokeJoin,StrokeCap,FillType}=require('@napi-rs/canvas');
const root=path.resolve(__dirname,'..');const src=fs.readFileSync(path.join(root,'sources/Michroma-Regular.ttf'));
const tabs={};for(let i=0;i<src.readUInt16BE(4);i++){let o=12+16*i;tabs[src.toString('ascii',o,o+4)]=Buffer.from(src.subarray(src.readUInt32BE(o+8),src.readUInt32BE(o+8)+src.readUInt32BE(o+12)));}
const U=tabs.head.readUInt16BE(18),N=tabs.maxp.readUInt16BE(4),long=tabs.head.readInt16BE(50),nMetrics=tabs.hhea.readUInt16BE(34);
const offsets=Array.from({length:N+1},(_,i)=>long?tabs.loca.readUInt32BE(i*4):tabs.loca.readUInt16BE(i*2)*2);
const cache=new Map();
function contours(gid,depth=0){if(cache.has(gid))return cache.get(gid);if(depth>15)throw Error('Composite cycle');let b=tabs.glyf.subarray(offsets[gid],offsets[gid+1]);if(!b.length)return[];let n=b.readInt16BE(0),out=[];
 if(n>=0){let o=10,ends=[];for(let i=0;i<n;i++,o+=2)ends.push(b.readUInt16BE(o));let ins=b.readUInt16BE(o);o+=2+ins;let count=n?ends[n-1]+1:0,flags=[];while(flags.length<count){let f=b[o++];flags.push(f);if(f&8){let rep=b[o++];while(rep--)flags.push(f);}}let xs=[],ys=[],v=0;for(let f of flags){v+=(f&2)?((f&16)?1:-1)*b[o++]:((f&16)?0:b.readInt16BE(o));if(!(f&2)&&!(f&16))o+=2;xs.push(v);}v=0;for(let f of flags){v+=(f&4)?((f&32)?1:-1)*b[o++]:((f&32)?0:b.readInt16BE(o));if(!(f&4)&&!(f&32))o+=2;ys.push(v);}let start=0;for(let end of ends){out.push(Array.from({length:end-start+1},(_,j)=>({x:xs[start+j],y:ys[start+j],on:!!(flags[start+j]&1)})));start=end+1;}
 }else{let o=10,f;do{f=b.readUInt16BE(o);let id=b.readUInt16BE(o+2);o+=4;let a,bv;if(f&1){a=(f&2)?b.readInt16BE(o):b.readUInt16BE(o);bv=(f&2)?b.readInt16BE(o+2):b.readUInt16BE(o+2);o+=4;}else{a=(f&2)?b.readInt8(o):b[o];bv=(f&2)?b.readInt8(o+1):b[o+1];o+=2;}let xx=1,yy=1,xy=0,yx=0;if(f&8){xx=yy=b.readInt16BE(o)/16384;o+=2;}else if(f&64){xx=b.readInt16BE(o)/16384;yy=b.readInt16BE(o+2)/16384;o+=4;}else if(f&128){xx=b.readInt16BE(o)/16384;yx=b.readInt16BE(o+2)/16384;xy=b.readInt16BE(o+4)/16384;yy=b.readInt16BE(o+6)/16384;o+=8;}let comp=contours(id,depth+1).map(c=>c.map(p=>({x:p.x*xx+p.y*xy,y:p.x*yx+p.y*yy,on:p.on})));let dx=a,dy=bv;if(!(f&2)){let prev=out.flat()[a],pt=comp.flat()[bv];dx=prev.x-pt.x;dy=prev.y-pt.y;}out.push(...comp.map(c=>c.map(p=>({...p,x:p.x+dx,y:p.y+dy}))));}while(f&32);}
 cache.set(gid,out);return out;}
function toPath(cs){let p=new Path2D();for(let c of cs){if(!c.length)continue;let first=c[0],last=c[c.length-1];let start=first.on?first:last.on?last:{x:(first.x+last.x)/2,y:(first.y+last.y)/2};p.moveTo(start.x,start.y);let pts=first.on?c.slice(1):last.on?c.slice(0,-1):c.slice();pts.push({...start,on:true});for(let i=0;i<pts.length;i++){let a=pts[i];if(a.on)p.lineTo(a.x,a.y);else{let b=pts[i+1];if(b.on){p.quadraticCurveTo(a.x,a.y,b.x,b.y);i++;}else p.quadraticCurveTo(a.x,a.y,(a.x+b.x)/2,(a.y+b.y)/2);}}p.closePath();}return p;}
const mid=(a,b)=>[(a[0]+b[0])/2,(a[1]+b[1])/2];
function parseSVG(s){let tokens=s.match(/[a-zA-Z]|[-+]?(?:\d*\.\d+|\d+\.?\d*)(?:[eE][-+]?\d+)?/g)||[],i=0,cs=[],c=[],pos=[0,0];const pt=()=>[+tokens[i++],+tokens[i++]];const add=(p,on)=>c.push({x:Math.round(p[0]),y:Math.round(p[1]),on});
function cubic(p0,p1,p2,p3,d=0){let q=[(3*p1[0]-p0[0]+3*p2[0]-p3[0])/4,(3*p1[1]-p0[1]+3*p2[1]-p3[1])/4];let err=0;for(let t of [.25,.5,.75]){let u=1-t;for(let k=0;k<2;k++){let cu=u*u*u*p0[k]+3*u*u*t*p1[k]+3*u*t*t*p2[k]+t*t*t*p3[k],qu=u*u*p0[k]+2*u*t*q[k]+t*t*p3[k];err=Math.max(err,Math.abs(cu-qu));}}if(err<=.35||d>12){add(q,false);add(p3,true);}else{let a=mid(p0,p1),b=mid(p1,p2),cc=mid(p2,p3),dd=mid(a,b),e=mid(b,cc),f=mid(dd,e);cubic(p0,a,dd,f,d+1);cubic(f,e,cc,p3,d+1);}}
while(i<tokens.length){let cmd=tokens[i++];if(cmd==='M'){if(c.length)cs.push(c);c=[];pos=pt();add(pos,true);}else if(cmd==='L'){pos=pt();add(pos,true);}else if(cmd==='Q'){let q=pt();pos=pt();add(q,false);add(pos,true);}else if(cmd==='C'){let a=pt(),b=pt(),e=pt();cubic(pos,a,b,e);pos=e;}else if(cmd==='Z'||cmd==='z'){if(c.length>1&&c[0].x===c.at(-1).x&&c[0].y===c.at(-1).y)c.pop();if(c.length)cs.push(c);c=[];}else throw Error('Unsupported SVG '+cmd);}if(c.length)cs.push(c);return cs;}
function encode(cs){
const area=c=>c.reduce((v,p,i)=>{let q=c[(i+1)%c.length];return v+p.x*q.y-q.x*p.y},0);
const inside=(p,c)=>{let yes=false;for(let i=0,j=c.length-1;i<c.length;j=i++){let a=c[i],b=c[j];if((a.y>p.y)!=(b.y>p.y)&&p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x)yes=!yes;}return yes;};
const areas=cs.map(area);cs=cs.map((c,i)=>{const depth=cs.filter((other,j)=>j!==i&&Math.abs(areas[j])>Math.abs(areas[i])&&inside(c[0],other)).length;return ((areas[i]>0)!==(depth%2===0))?[...c].reverse():c;});
let points=cs.flat();if(!points.length)return{b:Buffer.alloc(0),bounds:[0,0,0,0],n:0,c:0};let xs=points.map(p=>p.x),ys=points.map(p=>p.y),bounds=[Math.min(...xs),Math.min(...ys),Math.max(...xs),Math.max(...ys)];let b=Buffer.alloc(12+cs.length*2+points.length*5);b.writeInt16BE(cs.length,0);bounds.forEach((v,j)=>b.writeInt16BE(v,2+2*j));let o=10,k=-1;for(let c of cs){k+=c.length;b.writeUInt16BE(k,o);o+=2;}b.writeUInt16BE(0,o);o+=2;for(let p of points)b[o++]=p.on?1:0;let prev=0;for(let p of points){b.writeInt16BE(p.x-prev,o);o+=2;prev=p.x;}prev=0;for(let p of points){b.writeInt16BE(p.y-prev,o);o+=2;prev=p.y;}return{b,bounds,n:points.length,c:cs.length};}
let chunks=[],loca=Buffer.alloc((N+1)*4),hmtx=Buffer.alloc(N*4),allBounds=[],maxPoints=0,maxContours=0,offset=0,manifest=[];
for(let gid=0;gid<N;gid++){let original=toPath(contours(gid)),bold=new Path2D(original);if(contours(gid).length){let outline=new Path2D(original);outline.stroke({width:U*.052,join:StrokeJoin.Miter,cap:StrokeCap.Butt,miterLimit:4});bold.op(outline,PathOp.Union);bold.simplify();bold.setFillType(FillType.EvenOdd);bold=bold.asWinding();bold.transform({a:1,b:0,c:0,d:.99,e:0,f:0});}
 let d=bold.toSVGString(),result=encode(parseSVG(d));loca.writeUInt32BE(offset,gid*4);let padded=Buffer.alloc((result.b.length+3)&~3);result.b.copy(padded);chunks.push(padded);offset+=padded.length;let adv=tabs.hmtx.readUInt16BE(Math.min(gid,nMetrics-1)*4);hmtx.writeUInt16BE(adv,gid*4);hmtx.writeInt16BE(result.bounds[0],gid*4+2);allBounds.push(result.bounds);maxPoints=Math.max(maxPoints,result.n);maxContours=Math.max(maxContours,result.c);manifest.push({gid,advance:adv,bounds:result.bounds,path:d});}
loca.writeUInt32BE(offset,N*4);tabs.glyf=Buffer.concat(chunks);tabs.loca=loca;tabs.hmtx=hmtx;tabs.head.writeInt16BE(1,50);tabs.head.writeUInt32BE(0,8);tabs.head.writeInt32BE(Math.round(.101*65536),4);tabs.head.writeUInt16BE(0,44);tabs.head.writeUInt16BE(tabs.head.readUInt16BE(16)&~16,16);
const total=[Math.min(...allBounds.map(b=>b[0])),Math.min(...allBounds.map(b=>b[1])),Math.max(...allBounds.map(b=>b[2])),Math.max(...allBounds.map(b=>b[3]))];total.forEach((v,j)=>tabs.head.writeInt16BE(v,36+2*j));
tabs.maxp=Buffer.alloc(32);tabs.maxp.writeUInt32BE(0x10000,0);tabs.maxp.writeUInt16BE(N,4);tabs.maxp.writeUInt16BE(maxPoints,6);tabs.maxp.writeUInt16BE(maxContours,8);tabs.maxp.writeUInt16BE(1,14);
tabs.hhea.writeUInt16BE(N,34);tabs.hhea.writeInt16BE(Math.max(tabs.hhea.readInt16BE(4),total[3]),4);tabs.hhea.writeInt16BE(Math.min(tabs.hhea.readInt16BE(6),total[1]),6);
const advs=manifest.map(g=>g.advance);tabs.hhea.writeUInt16BE(Math.max(...advs),10);tabs.hhea.writeInt16BE(Math.min(...allBounds.map(b=>b[0])),12);tabs.hhea.writeInt16BE(Math.min(...manifest.map(g=>g.advance-g.bounds[2])),14);tabs.hhea.writeInt16BE(Math.max(...allBounds.map(b=>b[2])),16);
tabs['OS/2'].writeUInt16BE(800,4);tabs['OS/2'].writeUInt16BE(0,8);let flags=tabs['OS/2'].readUInt16BE(62);tabs['OS/2'].writeUInt16BE((flags|64)&~(32|1),62);tabs['OS/2'].writeUInt16BE(Math.max(total[3],tabs['OS/2'].readUInt16BE(74)),74);tabs['OS/2'].writeUInt16BE(Math.max(-total[1],tabs['OS/2'].readUInt16BE(76)),76);if(tabs['OS/2'].length>=90){for(let o of[86,88])tabs['OS/2'].writeInt16BE(Math.round(tabs['OS/2'].readInt16BE(o)*.99+U*.026*.99),o);}
const names={0:'Copyright 2011 The Michroma Project Authors (https://github.com/googlefonts/Michroma-font). Modifications Copyright 2026 MARQUEE AI SYSTEMS.',1:'MARQUEE Heavy',2:'Regular',3:'0.101;MARQUEE;MARQUEEHeavy-Regular',4:'MARQUEE Heavy',5:'Version 0.101; Beta',6:'MARQUEEHeavy-Regular',8:'MARQUEE AI SYSTEMS',9:'Michroma Project Authors; derivative modifications by MARQUEE AI SYSTEMS',10:'A heavy display derivative of Michroma: 0.052em outline expansion and 99% vertical scale. Beta build. No Q underline in the font.',13:'This Font Software is licensed under the SIL Open Font License, Version 1.1. See OFL.txt.',14:'https://openfontlicense.org',16:'MARQUEE',17:'Heavy'};
let rec=[],strings=[],strOff=0;for(let [id,v]of Object.entries(names)){let bytes=Buffer.from(v,'utf16le');bytes.swap16();let r=Buffer.alloc(12);r.writeUInt16BE(3,0);r.writeUInt16BE(1,2);r.writeUInt16BE(0x409,4);r.writeUInt16BE(+id,6);r.writeUInt16BE(bytes.length,8);r.writeUInt16BE(strOff,10);strOff+=bytes.length;rec.push(r);strings.push(bytes);}let nh=Buffer.alloc(6);nh.writeUInt16BE(rec.length,2);nh.writeUInt16BE(6+rec.length*12,4);tabs.name=Buffer.concat([nh,...rec,...strings]);
for(let tag of ['fpgm','prep','cvt ','hdmx','VDMX','LTSH','DSIG'])delete tabs[tag];tabs.gasp=Buffer.from([0,1,0,1,255,255,0,10]);
function checksum(b){let sum=0;for(let i=0;i<b.length;i+=4){let v=0;for(let j=0;j<4;j++)v=(v*256+(b[i+j]||0))>>>0;sum=(sum+v)>>>0;}return sum;}
const tags=Object.keys(tabs).sort(),count=tags.length,pow=2**Math.floor(Math.log2(count));let header=Buffer.alloc(12+16*count);header.writeUInt32BE(0x10000);header.writeUInt16BE(count,4);header.writeUInt16BE(pow*16,6);header.writeUInt16BE(Math.log2(pow),8);header.writeUInt16BE(count*16-pow*16,10);let off=header.length,parts=[header],headOff;
tags.forEach((tag,j)=>{let b=tabs[tag],o=12+j*16;header.write(tag,o,4,'ascii');header.writeUInt32BE(checksum(b),o+4);header.writeUInt32BE(off,o+8);header.writeUInt32BE(b.length,o+12);if(tag==='head')headOff=off;let p=Buffer.alloc((b.length+3)&~3);b.copy(p);parts.push(p);off+=p.length;});let output=Buffer.concat(parts);output.writeUInt32BE((0xB1B0AFBA-checksum(output))>>>0,headOff+8);fs.writeFileSync(path.join(root,'fonts/MARQUEE-Heavy.ttf'),output);
// WOFF 1 wrapper, same outlines and metadata as the desktop font.
let wh=Buffer.alloc(44+20*count);wh.write('wOFF');wh.writeUInt32BE(0x10000,4);wh.writeUInt16BE(count,12);wh.writeUInt32BE(output.length,16);wh.writeUInt16BE(0,20);wh.writeUInt16BE(101,22);let wo=wh.length,wp=[wh];tags.forEach((tag,j)=>{let tOff=header.readUInt32BE(12+j*16+8),len=tabs[tag].length,b=output.subarray(tOff,tOff+len),compressed=zlib.deflateSync(b),data=compressed.length<b.length?compressed:b,o=44+j*20;wh.write(tag,o,4,'ascii');wh.writeUInt32BE(wo,o+4);wh.writeUInt32BE(data.length,o+8);wh.writeUInt32BE(b.length,o+12);wh.writeUInt32BE(checksum(tabs[tag]),o+16);let p=Buffer.alloc((data.length+3)&~3);data.copy(p);wp.push(p);wo+=p.length;});wh.writeUInt32BE(wo,8);fs.writeFileSync(path.join(root,'fonts/MARQUEE-Heavy.woff'),Buffer.concat(wp));
fs.writeFileSync(path.join(root,'sources/outlines.json'),JSON.stringify({unitsPerEm:U,glyphs:manifest}));console.log(JSON.stringify({glyphCount:N,unitsPerEm:U,maxPoints,maxContours,bytes:output.length,checksum:checksum(output).toString(16),bounds:total}));
